# Generated by Django 3.1.7 on 2021-07-09 17:25

import Contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacts', '0004_remove_contact_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactemail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='contactphone',
            name='id',
        ),
        migrations.AddField(
            model_name='contactemail',
            name='uuid',
            field=models.TextField(default=Contacts.models.uniqueID, editable=False, max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='contactphone',
            name='uuid',
            field=models.TextField(default=Contacts.models.uniqueID, editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
