# Generated by Django 3.1.7 on 2021-07-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSettings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='contact',
            new_name='contacts',
        ),
    ]
