# Generated by Django 3.1.7 on 2021-07-10 04:24

import UserSettings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSettings', '0003_auto_20210709_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installedapp',
            name='id',
        ),
        migrations.AddField(
            model_name='installedapp',
            name='uuid',
            field=models.TextField(default=UserSettings.models.uniqueID, editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
