# Generated by Django 3.1.7 on 2021-07-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSettings', '0004_auto_20210710_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapp',
            name='invoicing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pin',
            name='invoicing',
            field=models.BooleanField(default=False),
        ),
    ]
